### PR TITLE
Better readme and cleaner code

### PR DESCRIPTION
**Pull request by umamaistempo**
Removed some unused code, changed some variables to make it more explicit and rewrote README to make the examples more obvious (extra: pipelines :smile: )

### CODE REVIEW

**Comment by NikolaMandic** [comment]
tell me if you tested it out and I am not going to check
WARNING: this entire project might have bigger issues under the hood that make it not so usable like dealing with binaries and char lists

**Comment by NikolaMandic** [comment]
I just wrapped driver from their website

**Comment by dersturm** [comment]
Hello. I couldn't test yet (a bit busy with other things) but it should work (as all i did was changing indentation and variable names as you can see at the changes).

About the support to binaries and char lists etc, i may take a look at it in the following weeks

**Comment by NikolaMandic** [comment]
I'm kinda lazy at testing it now since I have to install stuff from scratch once you test it I'll merge

**Comment by dersturm** [comment]
Hello. Sorry for not testing it yet. I am a a bit busy working on a private project.

In those 2 months i've got (a bit) better with Elixir, so i am now able to do a better job on this.

Don't merge this PR yet, i'll be commiting more changes (including proper Ex_doc compatible documentation) and testing.

BTW, i checked Aerospike website and, as you said, unfortunately the Erlang driver is quite limited :disappointed: but this library, albeit (very) limited, may be of use for someone :smile:

**Comment by NikolaMandic** [comment]
well the only reason I made it is because I wanted to have this fancy dbase running with phoenix framework. So I tried saw there is much more work and now I would prefer mnesia than this thing with phoenix but if someone would like to read and dump stuff then it could be useful

**Comment by umamaistempo** [comment]
Sorry for no update for months on this PR, have been pretty busy and on my work's project we decided to use Ruby for the Aerospike service since it's client implements UDFs, Batches etc.

I even exchanged mail with Aerospike asking if there would be an update on their NIF to include those features but, besides a voip call, didn't get any return. I may take a look on it in the next year shall i be free (i wouldn't bet on this) and capable of understanding some lines of C code :grin:

**Comment by mememori** [comment]
Also, you can leave issue #2 to me, i'll certainly complete it before day 26 since i'll be spending my holidays doing nothing but elixir :grin:

**Comment by NikolaMandic** [comment]
@mememori just to mention I do not find this driver much usefull. I did it to try to see how it works while trying to get web app up and runing. But mnesia erlang's embeded library is much better thing to spend your time on. This could potentially be capable to take somethinig from aerospike.
I am not sure why would anybody use aerospike with erlang when there is mnesia except to dump something from it. No mather how speedy multithreaded or what not seems tough to beat mnesia

**Comment by umamaistempo** [comment]
I am aware about this (in my work's project we decided to use Aerospike to cache on the python side of the code and mnesia to hold data-to-be-processed on the elixir side).

But a proper aerospike driver for elixir/erlang would be useful for read-intensive storage (ie: cache) :smile:

**Comment by umamaistempo** [comment]
And for anyone reading this: aerospike erlang client is not good for this since it doesn't implement `batch`, `scan`, `query`, `udf` or `aggregation` features. And to be able to use those you would either have to update the aerospike NIF or use something like a port.

For this very reason, the aerospike erlang client is of not much use at all

http://www.aerospike.com/docs/guide/client_matrix.html

**Pull request merged**
